%%% start preambling . . .  %%%
\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%amoung other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citaions 
\usepackage[nottoc]{tocbibind} %should add Refences to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%alows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage[small]{caption}

\usepackage{xr-hyper} %refer to Fig.s in another document
\usepackage{hyperref}

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{Draft early 2022}
\fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {./Figures/} }% tell latex where to find photos 
\externaldocument[supp-]{Traitors_Manuscript_supp}

\begin{document}
\SweaveOpts{concordance=TRUE}


\section{Supplementary Material}

\subsection{Methods}

We used a phylogenetic generalized least-squares regression model (PGLS) to test the relationship between day of budburst and each trait. This analysis allowed us to test for phylogenetic non-independence in the phenology-trait relationship (Freckleton2002). We obtained a rooted phylogenetic tree by pruning the tree developed by (Smith2018a) and performed the PGLS analysis using the mean trait values and mean posterior estimates of the cue responses from our joint model. The PGLS was run using the "Caper" package in R (Orme2013). 


<<label=suppTableHt, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)

source("..//..//analyses/traits/Rfiles/sm_tables.R")
#get_variables(mdl.traitphen)

datasource <- print(xtable(tabTest , caption="Data sources"), include.rownames= F, caption.placement="top", hline.after=c(-1,0),tablular.environment = "longtable", xtable.floating = T)

# print(datasource,
#       include.rownames=FALSE, 
#       hline.after = c(-1,0,nrow(datasource)),
#       caption.placement="top",
#       tabular.environment = "longtable", 
#       floating = FALSE,
#       #align=c(rep('|c',  ncol(datasource)),'p{4in}'),
#       # tabular="\\textwidth",
#       include.colnames = TRUE, 
#       # add.to.row = list(pos = list(0),
#       #                   command = "\\hline \\endhead "),
#       # sanitize.text.function = identity
#       )
#  

 
@

\begin{figure}[h!]
    \centering
 \includegraphics[width=\textwidth]{..//..//analyses/traits/figures/PCA_geometricmean.png}
    \caption{A projection of tree traits across the first and second principle component axis. Arrows represent the direction of vectors for six functional traits. Points represent the 26 speices for which complete trait data was available}
    \label{figure:pca}
\end{figure}

\begin{figure}[h!]
    \centering
 \includegraphics[width=\textwidth]{..//..//analyses/traits/figures/FourTraitFit_37spp_wp.png} 
    \caption{Comparisons of estimated model fits and raw data from joint models of trait effects on budburst phenological cues for 37 species of woody deciduous plants. Four functional traits -- a. height, b. SLA, c. seed mass, and d. LNC -- were modelled individually, with the calculated trait value being used to jointly model species responses to standardized chilling, forcing, and photoperiod cues. Model posteriors are shown in black, with the thicker line depicting the 66\% interval and the thinner black line the 97\% interval. Overall species level model posterior distributions were well aligned with the raw data, shown in red, and the species level means from the raw data, denoted as a purple stars.}
    \label{figure:TraitDistributions}
\end{figure}

\begin{figure}[h!]
    \centering
 \includegraphics[width=\textwidth]{..//..//analyses/traits/figures/slopesConsAcqu_supp_concept.pdf} 
    \caption{Functional traits may contribute to the species responses to forcing, chilling, or photoperiod cues in several ways. a) If traits are contribute negatively to the timing of phenological events, we expect the phenological response to be stronger and budburst earlier with increasing cue values. b) But if traits have no effects on the timing of budburst then cue responses will be zero and equivalent to the cue only trends. c) Lastly, traits that have a positive contribution to the timing of phenological events produce weaker responses with later budburst dates. The effect of height on phenological cue responses was weaker in response to forcing cues, but stronger in response to both chilling and photoperiod. In contrast, seed mass has a negligble effect on forcing and photoperiod cue responses, but a greater response with chilling. Band represent the 50\% uncertainty intervals of the model estimates.}
    \label{supp-fig:slopes}
\end{figure}


<<label=suppTableHt, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)
load("..//..//analyses/traits/output/height_raw_37spp.Rda")
#get_variables(mdl.traitphen)

sumt <- summary(mdl.traitphen)$summary

col4table <- c("mean","sd","2.5%","50%","97.5%","Rhat")

mu_params <-   c("mu_grand",
                 "muPhenoSp",
                 "muForceSp", # muAlphaForce
                 "muChillSp",
                 "muPhotoSp",
                 "betaTraitxForce",
                 "betaTraitxChill",
                 "betaTraitxPhoto",
                 "sigma_sp",
                 "sigma_study",
                 "sigma_traity",
                 "sigmaPhenoSp",
                 "sigmaForceSp",
                 "sigmaChillSp",
                 "sigmaPhotoSp", #sigma_alpha_photo
                 "sigmapheno_y")
esti <- sumt[mu_params, col4table]

#temp <- c(mugrandtrait, muStudy, muGrandSpname, betaForceSpname)
rownames(esti) =c("mu_grand",
                  "muPhenoSp",
                  "muForceSp",
                  "muChillSp",
                  "muPhotoSp",
                  "betaTraitxForce",
                  "betaTraitxChill",
                  "betaTraitxPhoto",
                  "sigma_sp",
                  "sigma_study",
                  "sigma_traity",
                  "sigmaPhenoSp",
                  "sigmaForceSp",
                  "sigmaChillSp",
                  "sigmaPhotoSp",
                  "sigmapheno_y")

esti.table <- sumt[mu_params, col4table]
row.names(esti.table) <- row.names(esti)

print(xtable(esti.table , caption="Height model estimates"),include.rownames= T, caption.placement="top", hline.after=c(-1,0))
 
@
 

<<label=suppTableSLA, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)
load("..//..//analyses/traits/output/sla_raw_37spp.Rda")
#get_variables(mdl.traitphen)

sumt <- summary(mdl.traitphen)$summary

col4table <- c("mean","sd","2.5%","50%","97.5%","Rhat")

mu_params <-   c("mu_grand",
                 "muPhenoSp",
                 "muForceSp", # muAlphaForce
                 "muChillSp",
                 "muPhotoSp",
                 "betaTraitxForce",
                 "betaTraitxChill",
                 "betaTraitxPhoto",
                 "sigma_sp",
                 "sigma_study",
                 "sigma_traity",
                 "sigmaPhenoSp",
                 "sigmaForceSp",
                 "sigmaChillSp",
                 "sigmaPhotoSp", #sigma_alpha_photo
                 "sigmapheno_y")
esti <- sumt[mu_params, col4table]

#temp <- c(mugrandtrait, muStudy, muGrandSpname, betaForceSpname)
rownames(esti) =c("mu_grand",
                  "muPhenoSp",
                  "muForceSp",
                  "muChillSp",
                  "muPhotoSp",
                  "betaTraitxForce",
                  "betaTraitxChill",
                  "betaTraitxPhoto",
                  "sigma_sp",
                  "sigma_study",
                  "sigma_traity",
                  "sigmaPhenoSp",
                  "sigmaForceSp",
                  "sigmaChillSp",
                  "sigmaPhotoSp",
                  "sigmapheno_y")

esti.table <- sumt[mu_params, col4table]
row.names(esti.table) <- row.names(esti)

print(xtable(esti.table , caption="SLA model estimates"),include.rownames= T, caption.placement="top", hline.after=c(-1,0))
 
@

<<label= suppTableSeedMass, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)
load("..//..//analyses/traits/output/seedmasslog10_raw_37spp.Rda")
#get_variables(mdl.traitphen)

sumt <- summary(mdl.traitphen)$summary

col4table <- c("mean","sd","2.5%","50%","97.5%","Rhat")

mu_params <-   c("mu_grand",
                 "muPhenoSp",
                 "muForceSp", # muAlphaForce
                 "muChillSp",
                 "muPhotoSp",
                 "betaTraitxForce",
                 "betaTraitxChill",
                 "betaTraitxPhoto",
                 "sigma_sp",
                 "sigma_study",
                 "sigma_traity",
                 "sigmaPhenoSp",
                 "sigmaForceSp",
                 "sigmaChillSp",
                 "sigmaPhotoSp", #sigma_alpha_photo
                 "sigmapheno_y")
esti <- sumt[mu_params, col4table]

#temp <- c(mugrandtrait, muStudy, muGrandSpname, betaForceSpname)
rownames(esti) =c("mu_grand",
                  "muPhenoSp",
                  "muForceSp",
                  "muChillSp",
                  "muPhotoSp",
                  "betaTraitxForce",
                  "betaTraitxChill",
                  "betaTraitxPhoto",
                  "sigma_sp",
                  "sigma_study",
                  "sigma_traity",
                  "sigmaPhenoSp",
                  "sigmaForceSp",
                  "sigmaChillSp",
                  "sigmaPhotoSp",
                  "sigmapheno_y")

esti.table <- sumt[mu_params, col4table]
row.names(esti.table) <- row.names(esti)

print(xtable(esti.table , caption=" Log10 Seed mass model estimates"),include.rownames= T, caption.placement="top", hline.after=c(-1,0))
 
@

<<label= suppTableLNC, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)
load("..//..//analyses/traits/output/lnc_raw_37spp.Rda")
#get_variables(mdl.traitphen)

sumt <- summary(mdl.traitphen)$summary

col4table <- c("mean","sd","2.5%","50%","97.5%","Rhat")

mu_params <-   c("mu_grand",
                 "muPhenoSp",
                 "muForceSp", # muAlphaForce
                 "muChillSp",
                 "muPhotoSp",
                 "betaTraitxForce",
                 "betaTraitxChill",
                 "betaTraitxPhoto",
                 "sigma_sp",
                 "sigma_study",
                 "sigma_traity",
                 "sigmaPhenoSp",
                 "sigmaForceSp",
                 "sigmaChillSp",
                 "sigmaPhotoSp", #sigma_alpha_photo
                 "sigmapheno_y")
esti <- sumt[mu_params, col4table]

#temp <- c(mugrandtrait, muStudy, muGrandSpname, betaForceSpname)
rownames(esti) =c("mu_grand",
                  "muPhenoSp",
                  "muForceSp",
                  "muChillSp",
                  "muPhotoSp",
                  "betaTraitxForce",
                  "betaTraitxChill",
                  "betaTraitxPhoto",
                  "sigma_sp",
                  "sigma_study",
                  "sigma_traity",
                  "sigmaPhenoSp",
                  "sigmaForceSp",
                  "sigmaChillSp",
                  "sigmaPhotoSp",
                  "sigmapheno_y")

esti.table <- sumt[mu_params, col4table]
row.names(esti.table) <- row.names(esti)

print(xtable(esti.table , caption="LNC model estimates"),include.rownames= T, caption.placement="top", hline.after=c(-1,0))
 
@
\end{document}