%%% start preambling . . .  %%%
\documentclass{article}

% required 
\usepackage[hyphens]{url} 
\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage[sort&compress, numbers, super]{natbib}
\usepackage{amsmath}
\usepackage{textcomp}
\usepackage{float}
\usepackage[utf8]{inputenc} 
\usepackage[nottoc]{tocbibind} 
\usepackage{amsmath} 
\usepackage{listings} 
\usepackage{xcolor}
\usepackage{capt-of}
\usepackage[export]{adjustbox} 
\usepackage{lineno}
\usepackage{lscape}
\linenumbers
\usepackage[small]{caption}

\usepackage{xr-hyper} 
\usepackage{hyperref}

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{Draft early 2022}
\fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

\graphicspath{ {./Figures/} }% tell latex where to find photos 
\externaldocument{traitsPhenoSupp}

\begin{document}
\SweaveOpts{concordance=FALSE}

\renewcommand{\bibname}{References}%names reference list 
\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\thefigure}{S\arabic{figure}}

\section{Supplementary Material}

\subsection{Methods}

We used a phylogenetic generalized least-squares regression model (PGLS) to test the relationship between day of budburst and each trait. This analysis allowed us to test for phylogenetic non-independence in the phenology-trait relationship \citep{Freckleton2002}. We obtained a rooted phylogenetic tree by pruning the tree developed by \citep{Smith2018a} and performed the PGLS analysis using the mean trait values and mean posterior estimates of the cue responses from our joint model. The PGLS was run using the "Caper" package in R \citep{Orme2013}. \\

\bibliographystyle{refs/bibstyles/science.bst}% 
\bibliography{refs/traitors_mar23.bib}
\newpage

\begin{figure}[h!]
    \centering
 \includegraphics[width=\textwidth]{..//..//analyses/traits/figures/PCA_geometricmean.pdf}
    \caption{A projection of tree traits across the first and second principle component axis. Arrows represent the direction of vectors for six functional traits. Points represent the 26 species for which complete trait data was available}
    \label{fig:pca}
\end{figure}

\newpage
\begin{figure}[h!]
    \centering
 \includegraphics[width=\textwidth]{..//..//analyses/traits/figures/FourTraitFit_37spp_wp.png} 
    \caption{Comparisons of estimated model fits and raw data from joint models of trait effects on budburst phenological cues for 37 species of woody deciduous plants. Four functional traits -- a. height, b. SLA, c. seed mass, and d. LNC -- were modeled individually, with the calculated trait value being used to jointly model species responses to standardized chilling, forcing, and photoperiod cues. Model posteriors are shown in black, with the thicker line depicting the 66\% interval and the thinner black line the 97\% interval. Overall species level model posterior distributions were well aligned with the raw data, shown in red, and the species level means from the raw data, denoted as a purple stars.}
    \label{fig:TraitDistributions}
\end{figure}
\newpage

\begin{figure}[h!]
    \centering
 \includegraphics[width=\textwidth]{..//..//analyses/traits/figures/slopesConsAcqu_supp_concept.pdf} 
    \caption{Functional traits may contribute to the species responses to forcing, chilling, or photoperiod cues in several ways. a) If traits are contribute negatively to the timing of phenological events, we expect the phenological response to be stronger and budburst earlier with increasing cue values. b) But if traits have no effects on the timing of budburst then cue responses will be zero and equivalent to the cue only trends. c) Lastly, traits that have a positive contribution to the timing of phenological events produce weaker responses with later budburst dates. The effect of height on phenological cue responses was weaker in response to forcing cues, but stronger in response to both chilling and photoperiod. In contrast, seed mass has a negligible effect on forcing and photoperiod cue responses, but a greater response with chilling. Band represent the 50\% uncertainty intervals of the model estimates.}
    \label{fig:slopesSupp}
\end{figure}

\newpage
<<label=table1, echo=FALSE , results=tex>>=
require(xtable)
#get_variables(mdl.traitphen)
smTab37 <- read.csv("../../analyses/traits/input/sm_table_37spp.csv")
datasource <- print(xtable(smTab37 , caption="Bibliographic information for trait data sources from both BIEN and Try trait databases.", label = "tableDataSources"), include.rownames= F, caption.placement="top", hline.after=c(-1,0),tablular.environment = "longtable", xtable.floating = T)

 
@

<<label=suppTableHt, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)
load("..//..//analyses/traits/output/height_raw_37spp.Rda")
#get_variables(mdl.traitphen)

sumt <- summary(mdl.traitphen)$summary

col4table <- c("mean","sd","2.5%","50%","97.5%","Rhat")

mu_params <-   c("mu_grand",
                 "muPhenoSp",
                 "muForceSp", # muAlphaForce
                 "muChillSp",
                 "muPhotoSp",
                 "betaTraitxForce",
                 "betaTraitxChill",
                 "betaTraitxPhoto",
                 "sigma_sp",
                 "sigma_study",
                 "sigma_traity",
                 "sigmaPhenoSp",
                 "sigmaForceSp",
                 "sigmaChillSp",
                 "sigmaPhotoSp", #sigma_alpha_photo
                 "sigmapheno_y")
esti <- sumt[mu_params, col4table]

#temp <- c(mugrandtrait, muStudy, muGrandSpname, betaForceSpname)
rownames(esti) =c("mu_grand",
                  "muPhenoSp",
                  "muForceSp",
                  "muChillSp",
                  "muPhotoSp",
                  "betaTraitxForce",
                  "betaTraitxChill",
                  "betaTraitxPhoto",
                  "sigma_sp",
                  "sigma_study",
                  "sigma_traity",
                  "sigmaPhenoSp",
                  "sigmaForceSp",
                  "sigmaChillSp",
                  "sigmaPhotoSp",
                  "sigmapheno_y")

esti.table <- sumt[mu_params, col4table]
row.names(esti.table) <- row.names(esti)

print(xtable(esti.table , caption="Summary of model estimates using measurements of tree height for our 37 focal species ($n$ = 42781)"),include.rownames= T, caption.placement="top", hline.after=c(-1,0))
 
@
 

<<label=suppTableSLA, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)
load("..//..//analyses/traits/output/sla_raw_37spp.Rda")
#get_variables(mdl.traitphen)

sumt <- summary(mdl.traitphen)$summary

col4table <- c("mean","sd","2.5%","50%","97.5%","Rhat")

mu_params <-   c("mu_grand",
                 "muPhenoSp",
                 "muForceSp", # muAlphaForce
                 "muChillSp",
                 "muPhotoSp",
                 "betaTraitxForce",
                 "betaTraitxChill",
                 "betaTraitxPhoto",
                 "sigma_sp",
                 "sigma_study",
                 "sigma_traity",
                 "sigmaPhenoSp",
                 "sigmaForceSp",
                 "sigmaChillSp",
                 "sigmaPhotoSp", #sigma_alpha_photo
                 "sigmapheno_y")
esti <- sumt[mu_params, col4table]

#temp <- c(mugrandtrait, muStudy, muGrandSpname, betaForceSpname)
rownames(esti) =c("mu_grand",
                  "muPhenoSp",
                  "muForceSp",
                  "muChillSp",
                  "muPhotoSp",
                  "betaTraitxForce",
                  "betaTraitxChill",
                  "betaTraitxPhoto",
                  "sigma_sp",
                  "sigma_study",
                  "sigma_traity",
                  "sigmaPhenoSp",
                  "sigmaForceSp",
                  "sigmaChillSp",
                  "sigmaPhotoSp",
                  "sigmapheno_y")

esti.table <- sumt[mu_params, col4table]
row.names(esti.table) <- row.names(esti)

print(xtable(esti.table , caption="Summary of model estimates using measurements of specific leaf area for our 37 focal species ($n$ = 7656)."),include.rownames= T, caption.placement="top", hline.after=c(-1,0))
 
@

<<label= suppTableSeedMass, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)
load("..//..//analyses/traits/output/seedmasslog10_raw_37spp.Rda")
#get_variables(mdl.traitphen)

sumt <- summary(mdl.traitphen)$summary

col4table <- c("mean","sd","2.5%","50%","97.5%","Rhat")

mu_params <-   c("mu_grand",
                 "muPhenoSp",
                 "muForceSp", # muAlphaForce
                 "muChillSp",
                 "muPhotoSp",
                 "betaTraitxForce",
                 "betaTraitxChill",
                 "betaTraitxPhoto",
                 "sigma_sp",
                 "sigma_study",
                 "sigma_traity",
                 "sigmaPhenoSp",
                 "sigmaForceSp",
                 "sigmaChillSp",
                 "sigmaPhotoSp", #sigma_alpha_photo
                 "sigmapheno_y")
esti <- sumt[mu_params, col4table]

#temp <- c(mugrandtrait, muStudy, muGrandSpname, betaForceSpname)
rownames(esti) =c("mu_grand",
                  "muPhenoSp",
                  "muForceSp",
                  "muChillSp",
                  "muPhotoSp",
                  "betaTraitxForce",
                  "betaTraitxChill",
                  "betaTraitxPhoto",
                  "sigma_sp",
                  "sigma_study",
                  "sigma_traity",
                  "sigmaPhenoSp",
                  "sigmaForceSp",
                  "sigmaChillSp",
                  "sigmaPhotoSp",
                  "sigmapheno_y")

esti.table <- sumt[mu_params, col4table]
row.names(esti.table) <- row.names(esti)

print(xtable(esti.table , caption="Summary of model estimates using measurements of seed mass data for our 37 focal species ($n$ = 281)."),include.rownames= T, caption.placement="top", hline.after=c(-1,0))
 
@

<<label= suppTableLNC, echo=FALSE , results=tex>>=
require(xtable)
require(rstan)
load("..//..//analyses/traits/output/lnc_raw_37spp.Rda")
#get_variables(mdl.traitphen)

sumt <- summary(mdl.traitphen)$summary

col4table <- c("mean","sd","2.5%","50%","97.5%","Rhat")

mu_params <-   c("mu_grand",
                 "muPhenoSp",
                 "muForceSp", # muAlphaForce
                 "muChillSp",
                 "muPhotoSp",
                 "betaTraitxForce",
                 "betaTraitxChill",
                 "betaTraitxPhoto",
                 "sigma_sp",
                 "sigma_study",
                 "sigma_traity",
                 "sigmaPhenoSp",
                 "sigmaForceSp",
                 "sigmaChillSp",
                 "sigmaPhotoSp", #sigma_alpha_photo
                 "sigmapheno_y")
esti <- sumt[mu_params, col4table]

#temp <- c(mugrandtrait, muStudy, muGrandSpname, betaForceSpname)
rownames(esti) =c("mu_grand",
                  "muPhenoSp",
                  "muForceSp",
                  "muChillSp",
                  "muPhotoSp",
                  "betaTraitxForce",
                  "betaTraitxChill",
                  "betaTraitxPhoto",
                  "sigma_sp",
                  "sigma_study",
                  "sigma_traity",
                  "sigmaPhenoSp",
                  "sigmaForceSp",
                  "sigmaChillSp",
                  "sigmaPhotoSp",
                  "sigmapheno_y")

esti.table <- sumt[mu_params, col4table]
row.names(esti.table) <- row.names(esti)

print(xtable(esti.table , caption="Summary of model estimates using measurements of leaf nitrogen content for our 37 focal species ($n$ = 3853.)"),include.rownames= T, caption.placement="top", hline.after=c(-1,0))
 
@


\end{document}