library(MASS)
library(aod)
library(car)
library(pbkrtest)
setwd("C:/Users/Harold/Documents/github/eysterthesis")
germs<- read.csv("germs.csv", header=TRUE)
modrateliPLALANg<-glmmPQL(germinated~origin*as.factor(temp)*strat, random=~1|location/uniqind, family=binomial(link="logit"), data=subset(germs, sp=="PLALAN" & sp!="PLAMED" & sp!="PLACOR"))
summary(modrateliPLALANg)
Anova(modrateliPLALANg)
modrateliPLALANgl<-glmer(germinated~origin*as.factor(temp)*strat+(1|location/uniqind), family=binomial(link="logit"), data=subset(germs, sp=="PLALAN" & sp!="PLAMED" & sp!="PLACOR"))
Anova(modrateliPLALANgl)
anova(modrateliPLALANgl)


modrateliPLALAN<-lmer(germinated~origin*as.factor(temp)*strat+(1|location/uniqind), family=binomial(link="logit"), data=subset(germs, sp==""))
df.KR <- get_ddf_Lb(modrateliPLALAN4, fixef(modrateliPLALAN4))
modrateliPLALANg<-glmmPQL(germinated~origin*as.factor(temp)*strat, random=~1|location/uniqind, data=subset(germs, sp=="PLALAN" & sp!="PLAMED" & sp!="PLACOR"))
summary(modrateliPLALANg)
summary(modrateliPLALANr)
View(germs)
library(ez)
modrateliCAPBURg<-glmmPQL(germinated~origin*as.factor(temp)*strat, random=~1|location/uniqind, family=binomial(link="logit"), data=subset(germs, sp=="PLAMAJ" & sp!="PLAMED" & sp!="PLACOR"))

modrateliPLALANn<-lme(germinated~origin*as.factor(temp)*strat, random=~1|location/uniqind, data=subset(germs, sp=="PLALAN"))
